name: 'Bump & Publish'

on:
  push:
    paths:
    - '*.js'
    - 'package.json'
    - 'yarn.lock'
    - '.github/workflows/publish.yml'
    - '.releaserc'
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  publish:
    name: 'Bump & Publish'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PLURAL_BOT_PAT }}
    - name: Read Node.js version from package.json
      run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
      id: engines
    - name: 'Setup Node'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.engines.outputs.nodeVersion }}
        registry-url: 'https://registry.npmjs.org'
    - name: 'Install Dependencies'
      run: yarn install --immutable
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.PLURAL_BOT_PAT }}
        NODE_AUTH_TOKEN: ${{ secrets.PLURAL_BOT_NPM_TOKEN }}
